version: '3.9'
services:
  downloader:
    build: .
    restart: always
    ports:
      - '8000:8000'
    command: bash -c "
        python manage.py collectstatic --noinput
        && python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/src