# Generated by Django 4.1.5 on 2023-01-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeDownloader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('choice', models.BooleanField()),
                ('av', models.BooleanField()),
                ('excepttions', models.CharField(max_length=50)),
            ],
        ),
    ]
