# Generated by Django 4.1.5 on 2023-01-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeDownloader',
        ),
    ]
